id = "exograph"
name = "Exograph"
version = "0.0.1"
schema_version = 1
authors = ["Affan Shahid <affan.shahid.94@gmail.com>"]
description = "Exograph syntax highlighting."
repository = "https://github.com/exograph/zed-extension"

[grammars.exograph]
repository = "https://github.com/exograph/tree-sitter-grammar"
commit = "<TODO>"
