name = "Exograph"
grammar = "exograph"
path_suffixes = ["exo"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = false, newline = true, not_in = [
        "string",
        "comment",
    ] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "/*", end = " */", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
]
tab_size = 2
